
services:
  traefik:
    image: traefik:v2.10
    restart: always
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"  # Allow API access (only for debugging)
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=augustosalazar@uninorte.edu.co"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"

    volumes:
      - "./traefik/dynamic.yml:/etc/traefik/dynamic.yml"
      - "./letsencrypt:/letsencrypt"

  homepage:
    image: nginx:alpine
    restart: always
    volumes:
      - "./html:/usr/share/nginx/html:ro"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/`)"
      - "traefik.http.routers.homepage.entrypoints=websecure"
      - "traefik.http.routers.homepage.tls.certresolver=letsencrypt"