http:
  middlewares:
    # Middleware to strip project paths before forwarding requests
    strip-bixa:
      stripPrefix:
        prefixes:
          - "/bixa"

    strip-jsonfy:
      stripPrefix:
        prefixes:
          - "/jsonfy"

    strip-silvy:
      stripPrefix:
        prefixes:
          - "/silvy"

    # Middleware to rewrite asset paths for all projects
    rewrite-assets:
      replacePathRegex:
        regex: "^/(main\\.js|main\\.css|.*\\.png|.*\\.jpg|.*\\.ico|.*\\.woff2|.*\\.svg|.*\\.ttf|.*\\.eot|.*\\.otf)$"
        replacement: "/{1}/{2}"

    # Security Headers to allow external stylesheets and correct CSP issues
    add-security-headers:
      headers:
        customResponseHeaders:
          Content-Security-Policy: "default-src 'self' https://unpkg.com; script-src 'self' 'unsafe-inline' https://unpkg.com; style-src 'self' 'unsafe-inline' https://unpkg.com; img-src 'self' data: https://unpkg.com; media-src 'self'; connect-src 'self'; font-src 'self' https://unpkg.com; object-src 'none'; frame-src 'none'; base-uri 'self'; form-action 'self'; manifest-src 'self'"
          Referrer-Policy: "no-referrer"
          X-Frame-Options: "SAMEORIGIN"
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"

  routers:
    homepage:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/`)"
      service: "homepage"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "add-security-headers"

    bixa:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/bixa`)"
      service: "bixa"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "strip-bixa"
        - "rewrite-assets"
        - "add-security-headers"

    jsonfy:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/jsonfy`)"
      service: "jsonfy"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "strip-jsonfy"
        - "rewrite-assets"
        - "add-security-headers"

    silvy:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/silvy`)"
      service: "silvy"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "strip-silvy"
        - "rewrite-assets"
        - "add-security-headers"

  services:
    homepage:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:80"

    bixa:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5002"

    jsonfy:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5003"

    silvy:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5004"
