http:
  middlewares:
    fix-bixa-path:
      replacePathRegex:
        regex: "^/bixa/?(.*)"
        replacement: "/$1"

    fix-jsonfy-path:
      replacePathRegex:
        regex: "^/jsonfy/?(.*)"
        replacement: "/$1"

    fix-silvy-path:
      replacePathRegex:
        regex: "^/silvy/?(.*)"
        replacement: "/$1"

    fix-missing-assets:
      redirectRegex:
        regex: "^/(main\\.css|main\\.js|favicon\\.ico)$"
        replacement: "/bixa/$1"
        permanent: false

  routers:
    homepage:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && Path(`/`)"
      service: "homepage"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"

    bixa:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/bixa`)"
      service: "bixa"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "fix-bixa-path"
        - "fix-missing-assets"

    jsonfy:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/jsonfy`)"
      service: "jsonfy"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "fix-jsonfy-path"

    silvy:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/silvy`)"
      service: "silvy"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "fix-silvy-path"

  services:
    homepage:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1"

    bixa:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5002"

    jsonfy:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5003"

    silvy:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5004"
