http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https

  routers:
    homepage:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/`)"
      service: "homepage"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"

    bixa:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/bixa`)"
      service: "bixa"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"

    jsonfy:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/jsonfy`)"
      service: "jsonfy"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"

    silvy:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/silvy`)"
      service: "silvy"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"

  services:
    homepage:
      loadBalancer:
        servers:
          - url: "http://homepage"

    bixa:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5002"

    jsonfy:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5003"

    silvy:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5004"
