http:
  middlewares:
    strip-bixa:
      stripPrefix:
        prefixes:
          - "/bixa"

    strip-jsonfy:
      stripPrefix:
        prefixes:
          - "/jsonfy"

    strip-silvy:
      stripPrefix:
        prefixes:
          - "/silvy"

    rewrite-bixa-assets:
      replacePathRegex:
        regex: "^/(main\\.js|main\\.css|app\\.js|.*\\.png|.*\\.jpg|.*\\.ico|.*\\.woff2)$"
        replacement: "/bixa/$1"

    rewrite-jsonfy-assets:
      replacePathRegex:
        regex: "^/jsonfy/(.*)$"
        replacement: "/$1"

    rewrite-silvy-assets:
      replacePathRegex:
        regex: "^/silvy/(.*)$"
        replacement: "/$1"

  routers:
    homepage:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/`)"
      service: "homepage"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"

    bixa:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/bixa`)"
      service: "bixa"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "strip-bixa"
        - "rewrite-bixa-assets"

    jsonfy:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/jsonfy`)"
      service: "jsonfy"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "strip-jsonfy"
        - "rewrite-jsonfy-assets"

    silvy:
      rule: "Host(`proyectosingenieria.uninorte.edu.co`) && PathPrefix(`/silvy`)"
      service: "silvy"
      entryPoints:
        - "websecure"
      tls:
        certResolver: "letsencrypt"
      middlewares:
        - "strip-silvy"
        - "rewrite-silvy-assets"

  services:
    homepage:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:80"

    bixa:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5002"

    jsonfy:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5003"

    silvy:
      loadBalancer:
        servers:
          - url: "http://172.17.0.1:5004"
